### ISSUE TITLE
how can I use it?

### ISSUE THREAD

**Issue by farvardin** [ook/otp_recover_secret#5]
I've compiled the binary, yet when I've looked how to use it, I see I have to get the URL of the QR code generated by Google Authenticator. But when I ask to export accounts from my phone, I only get a screen of a QR Code, with no URL or data which I could use with otp_recover_secret.

**Comment by ook** [comment]
You can use any QR code application to "see" the string encoded into the QR Code. On Android I use QRDroid, on web I used once https://www.patrick-wied.at/static/qrgen/

**Comment by farvardin** [comment]
thank you, it worked! 

I was expecting to be able to get the string from the same phone, but I had to use a second phone with barcode scanner to get the data!

I managed to migrate all my google authenticator data to the free and open source FreeOTP+ app!

**Comment by ook** [comment]
Happy it helped :)
